name: frontend-master workflow

on: 
  push:
    branches:
      - "newfeature_branch"
  pull_request:
    types:
      - "opened"
jobs:
  Running_backend:
     runs-on: ubuntu-latest
     steps:
      - name: getting codes
        uses: actions/checkout@v4
      - name: installing nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: running code
        run: |
          cd /home/runner/work/WWA_Pipeline/WWA_Pipeline/WWA-backend-master
          sudo npm i
          sudo npm run test  

  building_frontend:
   # needs: Running_backend
    runs-on: ubuntu-latest
    steps:
      - name: getting code
        uses: actions/checkout@v4
      - name: installing nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: installing  dependencies
        run: |
          cd /home/runner/work/WWA_Pipeline/WWA_Pipeline/WWA-frontend-master
          npm install 
          sudo npm run build 

  Automated_document:
     # needs: [Running_backend, building_frontend]
      runs-on: ubuntu-latest
      steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build
        uses: andstor/jsdoc-action@v1  

      - name: Generate Documentations
        run: |
          cd /home/runner/work/WWA_Pipeline/WWA_Pipeline/WWA-frontend-master
          npm install -g jsdoc
          npm install 
          npm run docs  

  Running_docker:
    runs-on: ubuntu-latest
    steps:
      - name: pulling image from docker 
        run: docker pull pavanvarikolu/wwafrontend:v1.0

      - name: building container
        run: docker run --name wwafrontendapp -p 3000:3000 -d pavanvarikolu/wwafrontend:v1.0

  


   